services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./messages.db:/app/messages.db
    environment:
      - RABBITMQ_HOST=rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
    volumes:
      - ./messages.db:/app/messages.db
    environment:
      - RABBITMQ_HOST=rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - rabbitmq
    volumes:
      - ./messages.db:/app/messages.db
    environment:
      - RABBITMQ_HOST=rabbitmq